### ISSUE TITLE
create-repo fails if ECR repository already exists 

### ISSUE THREAD

**Issue by schmiman** [CircleCI-Public/aws-ecr-orb#221] opened 2022-08-18 03:25 UTC
### Orb version 
circleci/aws-ecr@8.1.2

### What happened

With the create-repo tag, the build fails if the repo already exists.

    steps:
      - setup_remote_docker 
      - aws-ecr/build-and-push-image:
          region: ap-southeast-1
          create-repo: true
          assume-web-identity: true
          role-arn: arn:aws:iam::xxxxxx:role/xxxxxx-role
          repo: pdf-service
          repo-scan-on-push: true
          tag: <<parameters.imageTag>>
          skip-when-tags-exist: false

I even tried with deleting the existing repo and let circleCI create it. But even then it fails at the second run.

### Expected behavior

Only create the repo if it doesn't exist.
If the repot exists, continue and use the existing repo.

**Comment by p0tr3c** [comment] 2022-11-09 22:54
I am experiencing the same issue.

**Comment by brivu** [comment] 2022-11-24 09:02
Hey @p0tr3c and @schmiman, 

I am a little confused with what you mean by `tag` below: 

> ### What happened
> With the create-repo tag, the build fails if the repo already exists.

Is the job failing because the `repo` name already exists but only with a different `tag`?  

Or did you mean that when the `create-repo` parameter is `true`, the job fails if the `repo` name already exists?

Let me know so I can fix this issue in our next release!

Best, 
Brian

**Comment by schmiman** [comment] 2022-12-05 06:55
Hi @brivu,

the latter.
The `create-repo` tag being true creates the repo successfully, however on the second run it fails because it already exists.

You can essentially run just once with this `create-repo` parameter.

Cheers,
Mike

**Comment by brivu** [comment] 2022-12-05 18:47
Hey @schmiman, 

If a repository exists when the `create-repo` parameter is `true`, it's expected to fail if the repository exists. If you're trying to run a job for a repository that already exists, just remove the `create-repo` parameter or set it to `false`. 

I'm going to close this issue for now but if there's something I am missing, feel free to reopen it and let me know.

Thanks!
Brian

**Closed by brivu** 2022-12-05 18:47 UTC
Labels: bug

**Comment by zwalker** [comment] 2023-10-26 00:41
The documentation for the `create-repo` options is misleading.

It says: "Should the repo be created if it does not exist?"

This indicates that the expected behavior is what the creator of this issue expected.  I also think this orb would be more useful of the `create-repo` options created a repo if it does not exist and uses an existing repo if it does not exist without and reconfiguration needed.

If this is not going to be changed, the documentation for the `create-repo` parameter should be changed to "Create a new repo and fail if a repo by the same name already exists"
