### ISSUE TITLE
Unable to use aws-ecr/build_and_push_image in jobs

### ISSUE THREAD

**Issue by DanRoestorf** [CircleCI-Public/aws-ecr-orb#17] opened 2019-01-25 19:06 UTC
### Orb version

1.0.0

### What happened

I'm unable to use the aws-ecr/build_and_push_image command in a command or a job directly, it only works in the workflow.

Here's an example of my CircleCI config:

```
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@1.0.0

commands:
  build-push:
    description: "Build Docker image and push to ECR"
    parameters:
      repo:
        type: string
      dockerfile:
        type: string
    steps:
      - aws-ecr/build_and_push_image:
          repo: << parameters.repo >>
          dockerfile: << parameters.dockerfile >>

jobs:
  build-push:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - build-push:
          repo: "demo"
          dockerfile: "demo/Dockerfile"

workflows:
  build-deploy:
    jobs:
      - build-push:
          context: dev-global
```

When ran CircleCI errors out and outputs this:

```
#!/bin/sh -eo pipefail
# Error calling workflow: 'build-deploy'
# Error calling job: 'build-push-backend'
# Error calling command: 'build-push'
# Cannot find a definition for command named aws-ecr/build_and_push_image
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false
Exited with code 1
```

### Expected behavior

The aws-ecr/build_and_push_image command should work in commands and jobs.

**Comment by DanRoestorf** [comment] 2019-01-25 20:03
After reviewing the code I see that `aws-ecr/build_and_push_image` is only available as a job and not a command.

Would it be possible to expose this as a command? My configuration handles the deployment of multiple services in the repo and I would like to extract this step to a command.

**Comment by Tybot204** [comment] 2019-01-25 20:43
I also was having this issue trying to configure an orb I am writing for internal use on some projects. I would like to be able to create a job in my orb that calls this job with some preset parameters (which I believe would need to be exposed as a command to work).

**Comment by iynere** [comment] 2019-01-28 18:20
yes, @DanRoestorf the issue you identified initially was the intended behavior. when jobs are super all-encompassing, it's v v convenient (in my experience) to only have to call them in your `workflows` config. however, providing both a job & command is even better & allows for more modular use-cases.

that said, are you aware of our `pre-steps` & `post-steps` features ?

https://circleci.com/docs/2.0/reusing-config/#using-pre-and-post-steps

they allow you to call a job in your workflows config but add in custom steps before and afterwards

anyway, i've merged @Tybot204's PR, so the newest version of this orb should allow you do to what you want here:

https://circleci.com/orbs/registry/orb/circleci/aws-ecr

**Closed by iynere** 2019-01-28 18:20 UTC
