### ISSUE TITLE
When setting the profile-name property, ecr-login fails.

### ISSUE THREAD

**Issue by jeffnappi** [CircleCI-Public/aws-ecr-orb#9] opened 2019-01-12 20:37 UTC
If the `profile-name` setting is overridden, the build fails.

**Comment by iynere** [comment] 2019-01-16 18:43
thanks ! @jeffnappi i don't think we're currently integration-testing the orb with alternate profile names, let me set that up & that should help resolve this

**Comment by iynere** [comment] 2019-01-16 19:49
@jeffnappi can you be more specific about where the failure occurs ? feel free to link me to a job, so i can take a look

if the failure is towards the beginning, the bug may be in our [AWS CLI orb](https://circleci.com/orbs/registry/orb/circleci/aws-cli), not this one—otherwise, if it occurs later on, it's probably an issue with this orb

**Comment by iynere** [comment] 2019-01-16 19:55
hmmmm, i'm not able to reproduce @jeffnappi https://circleci.com/gh/CircleCI-Public/aws-ecr-orb/224

**Comment by jeffnappi** [comment] 2019-01-16 20:12
Hi! Thanks for taking a look, I will see if I can reproduce and get back to
you :)

**Comment by hollyhutson** [comment] 2019-08-23 05:09
@iynere we saw the same issue where failure occurs if `profile-name` is set. This occurs when trying to authenticate with ecr using get-login, I believe because the profile isn't set during this step.

**Comment by eddiewebb** [comment] 2020-01-30 16:32
@hollyhutson - thanks for the additional info, but the ECR login command uses this AWS command which does not support profiles - https://docs.aws.amazon.com/cli/latest/reference/ecr/get-login.html

Profile is specified at the time AWS CLI is configured by the underlying AWS orb.  https://github.com/CircleCI-Public/aws-ecr-orb/blob/master/src/commands/build-and-push-image.yml#L127

@jeffnappi / @hollyhutson - please include a sample config that sees this issue for us to diagnose further.  I'll mark this issue needing more details.

**Comment by sparta-developers** [comment] 2020-02-18 22:58
@eddiewebb We actually experimented with this and we can in fact pass `--profile`. The command is not specific to ECR `get-login`, but rather is picked up by the AWS CLI: https://docs.aws.amazon.com/cli/latest/reference/index.html#cli-aws

For clarity, we invoked the ECR get-login command from the build and push image step referenced here: https://github.com/CircleCI-Public/aws-ecr-orb/blob/master/src/commands/ecr-login.yml#L16
`aws ecr get-login --no-include-email --profile our_profile`

Let us know if you would like us to open up a PR.

**Comment by eddiewebb** [comment] 2020-02-19 17:46
Thank you @sparta-developers - that makes good sense.

we would love a PR, I see 2 paths, though you ,might see others

1) add profile as specific parameter.  This follows an established convention and addresses immediate need.
2) add a generic `arguments` to the command that could include --profule or other things.


#2 is more future proof but deviates from known patten, so #1 still feels like a good path.

**Comment by lokst** [comment] 2020-03-31 04:25
@sparta-developers Thank you for your contribution on this issue! We have just released `circleci/aws-ecr@6.8.0` based on your PR and hence will be closing this issue, and would encourage anyone who was following this issue to try out the new version!

**Closed by lokst** 2020-03-31 04:25 UTC
Labels: good first issue
